# This section specifies which data subsets to include.  Comment out any ones you want to omit.
subsets:
  #- 'OpenFF PEPCONF OptimizationDataset v1.0'
  - 'OpenFF Gen 2 Opt Set 1 Roche'
  - 'OpenFF Gen 2 Opt Set 2 Coverage'
  - 'OpenFF Gen 2 Opt Set 3 Pfizer Discrepancy'
  - 'OpenFF Gen 2 Opt Set 4 eMolecules Discrepancy'
  - 'OpenFF Gen 2 Opt Set 5 Bayer'


# This section specifies which data values to include.  The following are all of the most common choices.  Comment
# out ones you do not want.  Other less common values are also available.  For a full list of available values,
# and for descriptions of what each one means, see https://psicode.org/psi4manual/1.5.0/glossary_psivariables.html.
#values:
  #- 'DFT TOTAL ENERGY'
  #- 'DFT TOTAL GRADIENT'
  #- 'DISPERSION CORRECTION ENERGY'
  #- 'DISPERSION CORRECTION GRADIENT'
  #- 'MBIS CHARGES'
  #- 'MBIS DIPOLES'
  #- 'MBIS QUADRUPOLES'
  #- 'MBIS OCTUPOLES'
  #- 'SCF DIPOLE'
  #- 'SCF QUADRUPOLE'
  #- 'WIBERG LOWDIN INDICES'
  #- 'MAYER INDICES'


# This specifies a cutoff on forces.  A sample will be skipped if any component of the force on any atom
# is larger than this value (in hartree/bohr).  Comment out this line to include all samples regardless of
# force magnitude.
#max_force: 1.0
