# This section specifies which data subsets to include.  Comment out any ones you want to omit.
subsets:
  - 'SPICE PubChem Set 1 Single Points Dataset v1.2'
  - 'SPICE PubChem Set 2 Single Points Dataset v1.2'
  - 'SPICE PubChem Set 3 Single Points Dataset v1.2'
  - 'SPICE PubChem Set 4 Single Points Dataset v1.2'
  - 'SPICE PubChem Set 5 Single Points Dataset v1.2'
  - 'SPICE PubChem Set 6 Single Points Dataset v1.2'

# This section specifies which data values to include.  The following are all of the most common choices.  Comment
# out ones you do not want.  Other less common values are also available.  For a full list of available values,
# and for descriptions of what each one means, see https://psicode.org/psi4manual/1.5.0/glossary_psivariables.html.
values:
  - 'DFT TOTAL ENERGY'
  - 'DFT TOTAL GRADIENT'
  - 'DISPERSION CORRECTION ENERGY'
  - 'DISPERSION CORRECTION GRADIENT'
  #- 'MBIS CHARGES'
  #- 'MBIS DIPOLES'
  #- 'MBIS QUADRUPOLES'
  #- 'MBIS OCTUPOLES'
  #- 'SCF DIPOLE'
  #- 'SCF QUADRUPOLE'
  #- 'WIBERG LOWDIN INDICES'
  #- 'MAYER INDICES'